# Generated by Django 2.1.1 on 2019-06-16 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20190616_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='objects.building'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
