# Generated by Django 2.2.4 on 2019-08-28 17:00

from django.db import migrations
import objects.models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_remove_authorizationlist_for_rooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityQueue',
        ),
        migrations.AddField(
            model_name='authorizationlist',
            name='for_rooms',
            field=objects.models.PriorityQueue(default=False, verbose_name=objects.models.Teacher),
        ),
    ]
