# Generated by Django 2.2.4 on 2019-08-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Club',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_club',
        ),
        migrations.RemoveField(
            model_name='room',
            name='occupied',
        ),
    ]
