# Generated by Django 2.1.1 on 2019-06-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20190616_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='building',
            new_name='centre',
        ),
    ]
