# Generated by Django 2.2.4 on 2019-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_authorizationform_authorizationlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationlist',
            name='forrooms',
            field=models.ManyToManyField(to='objects.Teacher'),
        ),
    ]
