# Generated by Django 2.1.1 on 2019-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20190618_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='rooms',
        ),
        migrations.AddField(
            model_name='building',
            name='rooms',
            field=models.ManyToManyField(to='objects.room'),
        ),
    ]
