# Generated by Django 2.1.1 on 2019-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_auto_20190618_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='centre',
        ),
        migrations.AddField(
            model_name='building',
            name='room',
            field=models.ManyToManyField(to='objects.room'),
        ),
    ]
