# Generated by Django 2.1.1 on 2019-06-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_auto_20190621_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='centre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='objects.Building'),
            preserve_default=False,
        ),
    ]
