# Generated by Django 2.1.1 on 2019-06-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_auto_20190621_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.Building'),
        ),
    ]
